sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn install

script:
  - yarn run build
  - yarn run test

# Coveralls
after_success: yarn run coverage
